/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardUploadRouteImport } from './routes/dashboard.upload'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardQuizRouteImport } from './routes/dashboard.quiz'
import { Route as DashboardPlannerRouteImport } from './routes/dashboard.planner'
import { Route as DashboardHandwritingRouteImport } from './routes/dashboard.handwriting'
import { Route as DashboardFlashcardsRouteImport } from './routes/dashboard.flashcards'
import { Route as DashboardChatRouteImport } from './routes/dashboard.chat'
import { Route as DashboardAssignmentsRouteImport } from './routes/dashboard.assignments'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUploadRoute = DashboardUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQuizRoute = DashboardQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlannerRoute = DashboardPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHandwritingRoute = DashboardHandwritingRouteImport.update({
  id: '/handwriting',
  path: '/handwriting',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFlashcardsRoute = DashboardFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChatRoute = DashboardChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAssignmentsRoute = DashboardAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/assignments': typeof DashboardAssignmentsRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/flashcards': typeof DashboardFlashcardsRoute
  '/dashboard/handwriting': typeof DashboardHandwritingRoute
  '/dashboard/planner': typeof DashboardPlannerRoute
  '/dashboard/quiz': typeof DashboardQuizRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/assignments': typeof DashboardAssignmentsRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/flashcards': typeof DashboardFlashcardsRoute
  '/dashboard/handwriting': typeof DashboardHandwritingRoute
  '/dashboard/planner': typeof DashboardPlannerRoute
  '/dashboard/quiz': typeof DashboardQuizRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/assignments': typeof DashboardAssignmentsRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/flashcards': typeof DashboardFlashcardsRoute
  '/dashboard/handwriting': typeof DashboardHandwritingRoute
  '/dashboard/planner': typeof DashboardPlannerRoute
  '/dashboard/quiz': typeof DashboardQuizRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/upload': typeof DashboardUploadRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/dashboard/assignments'
    | '/dashboard/chat'
    | '/dashboard/flashcards'
    | '/dashboard/handwriting'
    | '/dashboard/planner'
    | '/dashboard/quiz'
    | '/dashboard/settings'
    | '/dashboard/upload'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/dashboard/assignments'
    | '/dashboard/chat'
    | '/dashboard/flashcards'
    | '/dashboard/handwriting'
    | '/dashboard/planner'
    | '/dashboard/quiz'
    | '/dashboard/settings'
    | '/dashboard/upload'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/dashboard/assignments'
    | '/dashboard/chat'
    | '/dashboard/flashcards'
    | '/dashboard/handwriting'
    | '/dashboard/planner'
    | '/dashboard/quiz'
    | '/dashboard/settings'
    | '/dashboard/upload'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/upload': {
      id: '/dashboard/upload'
      path: '/upload'
      fullPath: '/dashboard/upload'
      preLoaderRoute: typeof DashboardUploadRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/quiz': {
      id: '/dashboard/quiz'
      path: '/quiz'
      fullPath: '/dashboard/quiz'
      preLoaderRoute: typeof DashboardQuizRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/planner': {
      id: '/dashboard/planner'
      path: '/planner'
      fullPath: '/dashboard/planner'
      preLoaderRoute: typeof DashboardPlannerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/handwriting': {
      id: '/dashboard/handwriting'
      path: '/handwriting'
      fullPath: '/dashboard/handwriting'
      preLoaderRoute: typeof DashboardHandwritingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/flashcards': {
      id: '/dashboard/flashcards'
      path: '/flashcards'
      fullPath: '/dashboard/flashcards'
      preLoaderRoute: typeof DashboardFlashcardsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/chat': {
      id: '/dashboard/chat'
      path: '/chat'
      fullPath: '/dashboard/chat'
      preLoaderRoute: typeof DashboardChatRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/assignments': {
      id: '/dashboard/assignments'
      path: '/assignments'
      fullPath: '/dashboard/assignments'
      preLoaderRoute: typeof DashboardAssignmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAssignmentsRoute: typeof DashboardAssignmentsRoute
  DashboardChatRoute: typeof DashboardChatRoute
  DashboardFlashcardsRoute: typeof DashboardFlashcardsRoute
  DashboardHandwritingRoute: typeof DashboardHandwritingRoute
  DashboardPlannerRoute: typeof DashboardPlannerRoute
  DashboardQuizRoute: typeof DashboardQuizRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardUploadRoute: typeof DashboardUploadRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAssignmentsRoute: DashboardAssignmentsRoute,
  DashboardChatRoute: DashboardChatRoute,
  DashboardFlashcardsRoute: DashboardFlashcardsRoute,
  DashboardHandwritingRoute: DashboardHandwritingRoute,
  DashboardPlannerRoute: DashboardPlannerRoute,
  DashboardQuizRoute: DashboardQuizRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardUploadRoute: DashboardUploadRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
